# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Caps.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import numpy as np
import numpy.random as rnd


class Craps:
    def __init__(self):
        
    def Apostar(self, _mod):
        
        self.mod = _mod
        self.cuota = 0
        self.dinGanado = 0
        self.apuesta = 0
        self.saldo = 10000
        self.dado1 = rnd.randint(1,7,1)
        self.dado2 = rnd.randint(1,7,1)
        
        if self.mod == 1:
                self.cuota = 1.2
                if (self.dado1 + self.dado2 != 7)::
                    self.dinGanado = self.cuota * self.apuesta
        elif self.mod == 2:
            self.cuota = 1.5
            self.suma = self.dado1 + self.dado2
            if self.suma != 2 and self.suma != 3 and self.suma != 12:
                self.dinGanado = self.cuota * self.apuesta
        elif self.mod == 3:
            self.cuota = 2
            if ((self.dado1 % 2) == 0 or (self.dado2 % 2) == 0):
                self.dinGanado = self.cuota * self.apuesta
        elif self.mod == 4:
            self.repeat = True    
            self.cuota = 4.5
            while(repeat):
                self.dado1 = rnd.randint(1,7,1)
                self.dado2 = rnd.randint(1,7,1)
                if(self.dado1+self.dado2==7 or self.dado1+self.dado2==11):
                self.dinGanado = self.cuota * self.apuesta
                repeat = False
                elif(self.dado1+self.dado2==2 or self.dado1+self.dado2==3 or self.dado1+self.dado2==12):
                repeat = False
                else:
                repeat = True
        #elif self.mod == 5:
            #self.cuota = 36
            #Input UI, dado1=x, dado 2=y
            #if dado1 == dado1Player and dado2 == dado2Player or dado1 == dado2Player and dado2 == dado1Player:
                #self.dinGanado = self.cuota * self.apuesta
                
        self.saldo += self.dinGanado - self.apuesta
    def hahaprintxd(self):
        print("SIMEDISCULPANPROCEDOAXDDDDDD")

Juego = Craps()
Juego.Apostar(1)
print(Juego.dinGanado)
print(Juego.saldo)